### ISSUE TITLE
ROVER cannot reindex its data holding and make a subsequent request on Windows 10

### ISSUE THREAD

**Issue by timronan** [iris-edu/rover#110]
ROVER acts as expected when making an initial request in an empty data repo. Subsequent request do not seem to make it through the reindexing process and the subsuent request freezes at the step:
```
16:52:38.27>rover retrieve request.txt
retrieve  DEFAULT: ROVER version 1.0.3 - starting retrieve
retrieve  DEFAULT: Status available at http://127.0.0.1:8000
```

 it seems like the request is never posted to the web. 

Initial request is
```
IU ANMO * LHZ 2012-01-01T00:00:00 2012-02-01T00:00:00
TA MSTX -- BH? 2012-01-01T00:00:00 2012-02-01T00:00:00
```

Subsequent Request 
```
IU ANMO * LHZ 2012-01-01T00:00:00 2012-03-01T00:00:00
TA MSTX -- BH? 2012-01-01T00:00:00 2012-03-01T00:00:00
```
The end of the retrieve.txt log file with the verbosity set to 6. No critical error occurs but ROVER fails to make it past the indexing step.  
```
INFO     2019-05-20 16:52:41,818: Ensuring index is current before retrieval
DEBUG    2019-05-20 16:52:41,880: C:\Users\admin\Desktop\Projects\Rover_test\leap-seconds.list is 265712s old
INFO     2019-05-20 16:52:41,880: Indexing all changed files
DEBUG    2019-05-20 16:52:41,880: Execute: SELECT distinct filemodtime, filename FROM tsindex ORDER BY filename ASC, filemodtime DESC
```

**Comment by chad-iris** [comment]
I could not repeat this observation on Windows 10 (17763), using Miniconda and Python 3.7.3.

I did the first request and it worked as expected.  The second request downloaded the 2nd month of data as expected.

Side note: once mseedindex was built (installed into ..\Miniconda\Scripts\), ROVER worked really well in Windows with Miniconda 3.  I also put a Windows 10 mseedindex.exe on the Release page for mseedindex: https://github.com/iris-edu/mseedindex/releases, should anyone need it.

**Comment by timronan** [comment]
This error occurred because of an instance of mseedindex built using Cygwin. Use an mseed index instance built from the nmake program, or the released mseed index windows binary for best results.
