### ISSUE TITLE
Current rover source code is NOT compatible with python 2.7

### ISSUE THREAD

**Issue by baagaard-usgs** [iris-edu/rover#118]
I tried to install rover using Python 2.7, but I am finding a few areas where the code is using Python 3 features that are not compatible with Python 2.7.

Some examples of errors with Python 2.7:
  * `print(..., file=)` gives a syntax error (can be removed with a `from __future__import print_function()`)
  * `super()` (`super(CLASS, OBJECT)` is back compatible)

Since Python 2 is no longer supported, I suggest updating setup.py to require Python 3.

**Comment by chad-iris** [comment]
Hi @baagaard-usgs, how did you try to install ROVER?

Note that general installation directly from the source code is not supported.  The release packaging includes passing the code through `pasteurize` to make code that will run on both python 2.7 and 3.

Instead, installation is done via pip: https://pypi.org/project/rover/, as noted on the main project page: https://iris-edu.github.io/rover/

**Comment by baagaard-usgs** [comment]
Installing from pip does work with Python 2.7. Sorry for the confusion!

**Comment by chad-iris** [comment]
No problem.  Glad you got it worked out.
